spring:
  application:
    name: kanux-backend
  datasource:
    url: "jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?prepareThreshold=0&preferQueryMode=simple"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 1
      keepalive-time: 30000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: public
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    locations: classpath:db/migration
    url: "jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres"
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    root: INFO
    com.kanux: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

supabase:
  jwt-secret: ${SUPABASE_JWT_SECRET}
  url: ${SUPABASE_URL:https://amybrdlkfocmiolcnybl.supabase.co}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true

server:
  address: 0.0.0.0
  port: ${PORT:10000}
